# Generated by Django 5.0.6 on 2024-05-31 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('room_id', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('images', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facilities', models.TextField()),
                ('promo', models.TextField(blank=True, null=True)),
                ('area_or_location', models.CharField(max_length=255)),
                ('manager_id', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='manager_images/')),
                ('hotel_ownership_documents', models.TextField()),
                ('address_proof', models.TextField()),
                ('room_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cell', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('visited_u', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nid', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='user_images/')),
            ],
        ),
        migrations.CreateModel(
            name='HotelManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('facilities', models.TextField()),
                ('images', models.JSONField()),
                ('description', models.TextField()),
                ('approval_status', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='api.hotel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_hotels', to='api.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('available_rooms', models.IntegerField()),
                ('booked_rooms', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='api.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facilities', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.hotel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_id', models.IntegerField()),
                ('notification_type', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.IntegerField()),
                ('room_type', models.CharField(max_length=255)),
                ('member', models.BooleanField(default=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('booking_status', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.user')),
            ],
        ),
    ]
